jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    concurrency:
      group: build-group

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Install Visual Studio Build Tools (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install visualstudio2019buildtools
        choco install python3

    - name: Install Poetry
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          curl -sSL https://install.python-poetry.org | python -
          echo "C:\Users\runneradmin\AppData\Roaming\Python\Scripts" >> $GITHUB_PATH
        else
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        fi

    - name: Verify Poetry installation
      run: poetry --version

    - name: Cache build venv
      uses: actions/cache@v3
      with:
        path: example-app/.venv
        key: ${{ runner.os }}-venv

    - name: Install dependencies
      run: |
        cd example-app/
        poetry install --no-root

    - name: Install psycopg2-binary (Precompiled)
      run: |
        pip install psycopg2-binary==2.9.10 --only-binary :all:
