# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  # Job 1: Install dependencies
  install:
    runs-on: ubuntu-latest
    concurrency:
      group: install-group

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Cache build venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: example-app/.venv
        key: ${{ runner.os }}-venv

    - name: Install Poetry and dependencies
      run: |
        cd example-app/
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH=$PATH:$HOME/.local/bin
        poetry debug info
        poetry install --no-root

  # Job 2: Static code tests (linter, formatter, security)
  static-tests:
    runs-on: ubuntu-latest
    needs: install
    concurrency:
      group: static-tests-group

    steps:
    - uses: actions/checkout@v4

    - name: Cache build venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: example-app/.venv
        key: ${{ runner.os }}-venv

    - name: Run linter
      run: |
        cd example-app/
        poetry run flake8 .

    - name: Run formatter
      run: |
        cd example-app/
        poetry run black .

    - name: Security checks
      run: |
        cd example-app/
        poetry run bandit -r .

  # Job 3: Unit tests
  unittests:
    runs-on: ubuntu-latest
    needs: install
    concurrency:
      group: unittests-group

    steps:
    - uses: actions/checkout@v4

    - name: Cache build venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: example-app/.venv
        key: ${{ runner.os }}-venv

    - name: Run unit tests
      run: |
        cd example-app/
        poetry run pytest
